### ISSUE TITLE
Conflict with modern BSD queue.h when including uev.h in a program

### ISSUE THREAD

**Issue by troglobit** [troglobit/libuev#1]
Including `uev.h` causes conflict in programs that carry their own modern version of the BSD `queue.h` file.  This because libuEv uses the GNU LibC (older) version in `sys/queue.h`.

**Comment by troglobit** [comment]
One way around the problem is to make sure a newer version of `queue.h` is included *before* `uev.h` in your program.

The resolution to this may be that I need to distribute a modern version of `queue.h` with libuEv in the future.

**Comment by karasz** [comment]
sys/queue.h has yet another issue, namingly at least musl-libc does not distribute it so building libuev on musl based systems will fail.

**Comment by troglobit** [comment]
@karasz Ah, thanks for the heads-up! :+1: 

I've been kind of spoiled using only uClibc and EGLIBC over the years :innocent:

**Comment by troglobit** [comment]
Fixed in v1.0.5
