### ISSUE TITLE
Register new handlers on a running loop

### ISSUE THREAD

**Issue by SantjagoCorkez** [troglobit/libuev#11]
It's not quite clear after reading docs to me: Is it possible to register new EV-handlers inside other handlers of a running loop?

Suppose I have a running net socket which handles a message like "This is the address of an endpoint, go connect to it, send there a product of this `DATA`, report back the result". Of course EV-style (i.e. we don't wait for the endpoint to give a result to report it back to originator, instead we register a handler on that endpoint for messages coming from it in which we find out what's the originator's connection and send there a message with a product of that endpoint's response).

For example, `libuv` renders network handles stalled just after initialization if init inside a handler of an event of a running loop (https://github.com/libuv/libuv/issues/1505)

**Comment by troglobit** [comment]
As long as the socket/descriptor is non-blocking, registering a new handler is possible. 

I don't know what limitations libuv have, so cannot relate to that.

**Comment by SantjagoCorkez** [comment]
Thanks. I'll give it a try.

**Comment by troglobit** [comment]
Let me know how it goes so we can close this issue.

**Comment by troglobit** [comment]
@SantjagoCorkez did it work?

**Comment by troglobit** [comment]
Closing, no response in almost two weeks, assuming not a problem.

Please reopen should my assumption be incorrect.
