### ISSUE TITLE
#define ⇒ enum?

### ISSUE THREAD

**Issue by elfring** [troglobit/libuev#14]
Would you like to replace [any defines for constant values](https://github.com/troglobit/libuev/blob/fbcd200fd5d545bc4c4d9220bd88f8cf3c3560e8/src/uev.h#L33 "Update candidate") by [enumerations](https://en.wikipedia.org/wiki/Enumerated_type#C_and_syntactically_similar_languages) to stress their relationships?

**Comment by troglobit** [comment]
The constants referred to here are used for bitwise operations, enum cannot be used for this.

Closing w/o action.

**Comment by elfring** [comment]
I have got an other development opinion on this aspect.
