### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [troglobit/libuev#15]
I would like to point out that an identifier like “[`_SYS_QUEUE_H_`](https://github.com/troglobit/libuev/blob/7d6a37e4c56fe03c0493945aac0acfb87557c328/src/queue.h#L35 "Update candidate")” [does eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust the selection for unique names?

**Comment by troglobit** [comment]
The file `src/queue.h` is a `sys/queue.h` replacement, newer version of the *BSD queue API.  

Closing w/o action.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?
