### ISSUE TITLE
tests broken with gcc version 7.2?

### ISSUE THREAD

**Issue by oz123** [troglobit/libuev#16]
Hi, 
I have submitted an ebuild to gentoo with libuev. On my machines with gcc 5.4 everything works fine.

```
 $ gcc-config -l
 [1] x86_64-pc-linux-gnu-5.4.0 *
```
However, I have received a bug which reports breakage with x86_64-pc-linux-gnu-7.2.0. 
https://bugs.gentoo.org/640202

**Comment by troglobit** [comment]
You must have misfiled this. The Gentoo bug report is for libite, whereas this is the libuEv project. Please open an issue with libite instead.

(Also, I need more information to go on to debug that failing which test. My dev system is Ubuntu 17.10 which has GCC 7.2, and there the tests pass.)

**Comment by oz123** [comment]
@troglobit appologies ...

**Comment by troglobit** [comment]
No problem :)
