### ISSUE TITLE
timer-stop logic

### ISSUE THREAD

**Issue by M1cha** [troglobit/libuev#18]
I was looking at these 4 lines:
https://github.com/troglobit/libuev/blob/a334d23/src/uev.c#L381

```
if (!w->u.t.period)
	w->u.t.timeout = 0;
if (!w->u.t.timeout)
	uev_timer_stop(w);
```

To me this looks like when there's no initial timeout, and only a periodic timer, the timer just gets stopped after the first expiration.
Is that a bug or intended behavior?

**Comment by troglobit** [comment]
That is intended behavior, not really well documented though.  Setting timeout to zero disarms the timer. So for a periodic timer you have to set the initial delay as well.

The `uev_timer_init()` function calls `uev_timer_set()` (below):
https://github.com/troglobit/libuev/blob/a334d230a16ffd71921808e8eea48da88ec0f9ac/src/timer.c#L93-L105

**Comment by M1cha** [comment]
```
This is the underlying Linux function @func timerfd_settimer() which has this behavior. 
```
That part is not true though: https://linux.die.net/man/2/timerfd_settime
```
Setting either field of new_value.it_value to a nonzero value arms the timer. Setting both fields of new_value.it_value to zero disarms the timer.
```

**Comment by M1cha** [comment]
forget what I said. I didn't read properly and thought they were talking about "both" in the sense of "it_interval" and "it_value"
