### ISSUE TITLE
异步事件对共享资源同步性操作

### ISSUE THREAD

**Issue by pioneerAlone** [troglobit/libuev#19]
Hi!
After using libuev, I encountered some questions. After setting IO non-blocking to receive data, how do different events deal with shared resources?
For example, IO events, received data is dropped to databuf, data parsing event, read data from databuf for parsing, how to solve their synchronization

**Comment by troglobit** [comment]
Not sure I understand the use-case/problem, but I know some people use a `pipe()` to generate events for callbacks that depend on data/processing.  Unless you have multiple threads of execution, with one event loop per thread, then you may need to look into thread synchronization primitives.

**Comment by troglobit** [comment]
No response, closing ...
