### ISSUE TITLE
Regression: 'make install' stopped working in v1.0.5

### ISSUE THREAD

**Issue by karasz** [troglobit/libuev#2]
I successfuly built libuev on a musl based system after applying the folloving patch:
in essence removing test.c which was moved to examples dir.

    --- ./Makefile.orig     2015-02-15 18:30:30.000000000 +0100
    +++ ./Makefile  2015-02-15 21:12:03.081389097 +0100
    @@ -46,7 +46,7 @@
     libdir     ?= $(prefix)/lib
     datadir    ?= $(prefix)/share/doc/$(LIBNAME)
     incdir     ?= $(prefix)/include
    -DISTFILES   = README CHANGELOG TODO LICENSE test.c
    +DISTFILES   = README CHANGELOG TODO LICENSE
     HEADER      = uev.h
     
     OBJS       := uev.o io.o timer.o signal.o

**Comment by troglobit** [comment]
Ah, thanks!  :)

**Comment by troglobit** [comment]
Fixed on master, as of 312b825.
