### ISSUE TITLE
Not an issue just information about portability.

### ISSUE THREAD

**Issue by moe123** [troglobit/libuev#20]
Using the following: (1)  it runs perfectly on BSD's and BSD-like such as macos and ios; plus, recent Android sub-systems also seem to handle it properly (wasn't always the case as Android is maybe based on a linux kern, however, it departed from the original design to put it politely).

For windows, there is an existing epoll port; (2)  but I did not try it yet; don't know if it fairly runs. (These days windows support AF_UNIX or AF_LOCAL, see limitation about file-descriptor, so it would require some minor abstraction work, which is still better than libev plastering i.e only relaying on third party implementations of epoll; descriptor could be a struct holding the specific handle with the minimal set of i/o operations associated with mainly close and read... uev_epool_descriptor_t uev_epool_{}()).

edit info: possible cross-platform standalone unified-epool layer:
posix read/write syscalls Win32:
-- socket recv/send
-- I/O ReadFile/WriteFile support win-socket handles.

```
/* unified epoll front-end */

typedef struct
{
	SOCKET u_client;
	SOCKET u_listen;
} uepoll_socket_fd_t;

typedef union
{
	int    u_fd;
	HANDLE u_hnd;
} uepoll_file_fd_t;

typedef union
{
	uepoll_file_fd_t   u_file;
	uepoll_socket_fd_t u_sock;
} uepoll_fd_t;

typedef struct epoll_event uepoll_event_t;

/* unified I/O front-end */

uepoll_fd_t uepoll_open(const char * path, uepoll_fd_flag_t flag, ...)
{
// Case windows socket open rw;
	uepoll_fd_t fd;
	SOCKADDR_UN sock_un = { 0 };
	 
	if (INVALID_SOCKET != fd.u_sock.u_listen = socket(AF_UNIX, SOCK_STREAM, 0)) {
		sock_un.sun_family = AF_UNIX;
		strncpy_s(sock_un.sun_path, sizeof sock_un.sun_path, SERVER_SOCKET, (sizeof path) - 1);
		if (SOCKET_ERROR != bind(fd.u_sock.u_listen, (struct sockaddr *)&sock_un, sizeof(sock_un))) {
			if (SOCKET_ERROR != listen(fd.u_sock.u_listen, SOMAXCONN)) {
				if (INVALID_SOCKET != (fd.u_sock.u_client = accept(fd.u_sock.u_listen, NULL, NULL))) {
					...
				}
				...
			}
			...
		}
		...
	}
	...
}

uepoll_ssize_t uepoll_read(
	  uepoll_fd_t fildes
	, void *      buf
	, size_t      nbyte
);

uepoll_ssize_t uepoll_write(
	  uepoll_fd_t  fildes
	, const void * buf
	, size_t       nbyte
);

uepoll_fd_t uepoll_create(int size);
uepoll_fd_t uepoll_create1(int flags);

int uepoll_ctl(
	  uepoll_fd_t      epfd
	, int              op
	, uepoll_fd_t      fd
	, uepoll_event_t * event
);

int uepoll_wait(
	  uepoll_fd_t      epfd
	, uepoll_event_t * events
	, int              maxevents
	, int              timeout
);
```

1-  https://github.com/jiixyj/epoll-shim
2- https://github.com/piscisaureus/wepoll

I think, I am going to write a standalone draft document about making an unified header-only frontend where the heavy lift is handled by third-party implementations or native; if people want to join on puzzling what would be the best/fair approach you are welcome.

**Comment by troglobit** [comment]
Any progress on this?

**Comment by moe123** [comment]
Hello, a bit more, but still just snippet logs; the caveat is still to emulate fairly behaviors:  a socket handle under windows for read/write/poll mechanism is per see not so ideal; needs a non-blocking smooth event-looper; maybe going thru the NamedPipe win32 API is a more settled way. Unfortunately, in the past recent weeks, I didn't have a single second to power-on a windows machine to do some more concret diggings and then sketch some basic abstraction layer. I have been pretty buzzy handling over matters.

**Comment by troglobit** [comment]
OK.  Do you want to keep this issue open in the tracker?  I mean, I'll likely never do anything about this myself ... maybe a kqueue wrapper for porting my apps to *BSD, but that's way-way in the future and this seems better suited for a TODO or wishlist.

**Comment by moe123** [comment]
Hello, 

1 - I think it does hurt to let it open. You may move it in TODO if you prefer, myself, I like the flatten tree like organization (that's just me); as you wish.

2 - If you plan to bind against kqueue API, maybe on-boarding  the author of epoll-shim would be a good thing (I don't believe in wepoll author; seems to belong to another school of thinking). He went a bit messy but at least opened the way; I think going on/by the union type abstraction is the good trend; the "cleanest" one.

**Comment by troglobit** [comment]
Updated, referenced this issue for anyone circling back. Cheers
