### ISSUE TITLE
AM_CONFIG_HEADER is obsolete

### ISSUE THREAD

**Issue by alcir** [troglobit/libuev#22]
https://github.com/troglobit/libuev/blob/042f1b59bfa8dae71d3bffdf2bb88d1aea304d46/configure.ac#L7

AM_CONFIG_HEADER
    Automake will generate rules to automatically regenerate the config header. This obsolete macro is a synonym of AC_CONFIG_HEADERS today (see section 5.2 Other things Automake recognizes). 

https://ftp.gnu.org/old-gnu/Manuals/automake-1.7.2/html_chapter/automake_5.html#SEC23

**Comment by troglobit** [comment]
OK, I'll take that into consideration next time I iterate over the code for another release.

**Comment by troglobit** [comment]
Fixed in 08aa7dfd76, pull request #24.
