### ISSUE TITLE
CFLAGS in tests/Makefile.am

### ISSUE THREAD

**Issue by alcir** [troglobit/libuev#23]
https://github.com/troglobit/libuev/blob/042f1b59bfa8dae71d3bffdf2bb88d1aea304d46/tests/Makefile.am#L16

Just to know. Why "forcing" that instead of using flags used in the other Makefile?

**Comment by troglobit** [comment]
It started out in life as a local Makefile for tests I threw in there and then committed one day, forgetting to update/clean-up.
