### ISSUE TITLE
undefined reference to uev_*

### ISSUE THREAD

**Issue by paddor** [troglobit/libuev#26]
I configured, compiled, and installed libuev on Ubuntu 18.04 and 20.04. I did `sudo ldconfig`. `ldconfig -p` shows the library:

```
$ ldconfig -p |grep uev
        libuev.so.3 (libc6,x86-64) => /usr/local/lib/libuev.so.3
        libuev.so (libc6,x86-64) => /usr/local/lib/libuev.so
```

The library is there in /usr/local/include and /usr/local/lib and `pkg-config` gives me:

```
-D_TIME_BITS=64 -D_FILE_OFFSET_BITS=64 -I/usr/local/include -L/usr/local/lib -luev
```

But it still won't compile the example, which I've saved as `myTimer.c`.

```
$ gcc `pkg-config --libs --static --cflags libuev` -o myTimer myTimer.c
/usr/bin/ld: /tmp/ccceRUm9.o: in function `cb':
myTimer.c:(.text+0x31): undefined reference to `uev_timer_start'
/usr/bin/ld: /tmp/ccceRUm9.o: in function `main':
myTimer.c:(.text+0x6e): undefined reference to `uev_init'
/usr/bin/ld: myTimer.c:(.text+0x9c): undefined reference to `uev_timer_init'
/usr/bin/ld: myTimer.c:(.text+0xb0): undefined reference to `uev_run'
collect2: error: ld returned 1 exit status
```

Any ideas?

**Comment by troglobit** [comment]
It's the ordering to gcc.  You need to split it since you're building the way you do, without intermediate .o.  Like this:

     gcc `pkg-config --cflags libuev` -o myTimer myTimer.c `pkg-config --libs --static libuev`

Untested, but that's the way gcc/ld wants the args.

**Comment by paddor** [comment]
Thanks, I didn't know about that. But I'm still getting the same error.

**Comment by paddor** [comment]
Now it works. Command substitution in the Fish shell doesn't seem to always work as expected.

This is how it compiled:
```
gcc -D_TIME_BITS=64 -D_FILE_OFFSET_BITS=64 -I/usr/local/include -o myTimer myTimer.c -L/usr/local/lib -luev
```

**Comment by troglobit** [comment]
Glad you got it sorted 👍
