### ISSUE TITLE
Y2038: GLIBC 64-bit time_t on 32-bit platforms

### ISSUE THREAD

**Issue by vonj** [troglobit/libuev#9]
Possibly it could support 64 bit time_t with glibc with the help of __USE_TIME_BITS64?
Other libc's may follow.
(__USE_TIME_BITS64 is Glibc's time_t fix for 32 bit CPUs.)

Just thinking...

**Comment by troglobit** [comment]
Thanks, good idea to look into this!

**Comment by troglobit** [comment]
According to https://sourceware.org/glibc/wiki/Y2038ProofnessDesign GLIBC will enable `__USE_TIME_BITS64` if it sees `-D_TIME_BITS=64`.  So it should be safe to just set this in the `AM_CPPFLAGS` of the `Makefile.am` to automatically get the support on a newer GLIBC.

**Comment by troglobit** [comment]
I've been looking for some information on how uClibc and musl, the latter in particular, plan to handle `time_t` on aging 32-bit platforms.  Haven't really found anything ...
